name: Build and Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Install GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.3.0/gh_2.3.0_linux_amd64.tar.gz | tar xz -C . --strip-components=1 gh_2.3.0_linux_amd64/gh
        sudo mv gh /usr/local/bin/

    - name: Create GitHub Release
      run: |
        gh release create ${{ github.ref }} ./app/build/outputs/apk/release/app-release.apk -t "Release ${{ github.ref }}" -n "New release of the app."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
